# Simple workflow for deploying static content to GitHub Pages
name: Deploy Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # These steps will build the cargo documentation and store it in the "./docs/doc" folder,
    # and then the next step will create an "index.html" file in that folder which redirects to the "rssh" page.
    # After that, it will commit and push these changes to the "master" branch,
    # configure the GitHub Pages for the repository,
    # upload the artifact "./docs/doc" and
    # finally, deploy the documentation to the GitHub Pages.
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build cargo docs in docs/doc
        run: |
          cargo doc --no-deps --release --target-dir docs
          # TODO: # && rm -rf docs/release && cp docs/doc docs/ && rm -rf docs/doc
      - name: Create index.html in docs/doc
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=rssh\">  \n" > ./docs/doc/index.html
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          commit_message: "docs: add index.html and build cargo docs"
          branch: master
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/doc"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
